/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PurchaseManager;

import FinanceManager.PurchaseOrder;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author weisi
 */
public class PMPurchaseOrderManagerWindow extends javax.swing.JFrame {

    private PurchaseManager pm = new PurchaseManager();
//    private FMPurchaseOrder po = new FMPurchaseOrder();

    private void handleClose() {
        int option = JOptionPane.showConfirmDialog(
            this,
            "Do you want to save changes before closing?",
            "Confirm Exit",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (option == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tblPOs.getModel();
            List<String[]> data = new ArrayList<>();
            for (int i = 0; i < model.getRowCount(); i++) {
            String[] row = new String[12];
                for (int j = 0; j < 12; j++) {
                    row[j] = model.getValueAt(i, j).toString();
                }
                data.add(row);
            }
            pm.writeFile("PO.txt", data);
            JOptionPane.showMessageDialog(this, "Purchase orders saved.");
            dispose();
        } else if (option == JOptionPane.NO_OPTION) {
            dispose();
        }
        // If CANCEL or X clicked, do nothing
    }
    /**
     * Creates new form PurchaseOrderManagerWindow
     */
    public PMPurchaseOrderManagerWindow() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.setColumnIdentifiers(new String[] {
            "PO ID", "Item ID", "Item Name", "Quantity", 
            "Supplier ID","Supplier Name", "Requisition ID", "Unit Price (RM)", 
            "Total Price (RM)", "Date", "Status", "PM Name"
        });
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                handleClose();
            }
        });
        
        
        // Load existing POs
        List<PurchaseOrder> pos = pm.viewPO();
        for (PurchaseOrder po : pos) {
            model.addRow(new Object[] {
                po.getPoID(),
                po.getItemID(),
                po.getItemName(),
                po.getQuantity(),
                po.getSupplierID(),
                po.getSupplierName(),
                po.getprID(),  // Add this only if it's available in the object
                po.getPricePerUnit(),
                po.getTotal(),
                po.getDate(),
                po.getStatus(),
                po.getpmName() // Same as above: only if available in your class
            });
        }


        tblPOs.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPOs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPOID = new javax.swing.JTextField();
        txtRequisitionID = new javax.swing.JTextField();
        txtItemID = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPMName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtSupplierID = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tblPOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Titile 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        tblPOs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPOsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPOs);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Purchase Order List");

        txtPOID.setEditable(false);
        txtPOID.setBackground(new java.awt.Color(204, 204, 204));
        txtPOID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPOIDActionPerformed(evt);
            }
        });

        txtRequisitionID.setEditable(false);
        txtRequisitionID.setBackground(new java.awt.Color(204, 204, 204));
        txtRequisitionID.setDisabledTextColor(new java.awt.Color(255, 102, 255));
        txtRequisitionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRequisitionIDActionPerformed(evt);
            }
        });

        txtItemID.setEditable(false);
        txtItemID.setBackground(new java.awt.Color(204, 204, 204));

        txtQuantity.setEditable(false);
        txtQuantity.setBackground(new java.awt.Color(204, 204, 204));

        txtPMName.setEditable(false);
        txtPMName.setBackground(new java.awt.Color(204, 204, 204));
        txtPMName.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                txtPMNameComponentRemoved(evt);
            }
        });
        txtPMName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPMNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Purchase Order ID:");

        jLabel3.setText("Requisition ID:");

        jLabel4.setText("Item ID:");

        jLabel5.setText("Quantity:");

        jLabel6.setText("PM Name:");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel7.setText("Item Name:");

        jLabel8.setText("Supplier ID:");

        jLabel11.setText("Price:");

        txtItemName.setEditable(false);
        txtItemName.setBackground(new java.awt.Color(204, 204, 204));

        txtSupplierID.setEditable(false);
        txtSupplierID.setBackground(new java.awt.Color(204, 204, 204));
        txtSupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierIDActionPerformed(evt);
            }
        });

        txtUnitPrice.setEditable(false);
        txtUnitPrice.setBackground(new java.awt.Color(204, 204, 204));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(802, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtItemName)
                            .addComponent(txtPOID)
                            .addComponent(txtItemID)
                            .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPMName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRequisitionID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(375, 375, 375))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtRequisitionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtPMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSave))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPOIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOIDActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (btnEdit.getText().equals("Edit")) {
            int row = tblPOs.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to edit.");
                return;
            }
            // Enable text fields and chnage it colour
            txtQuantity.setEditable(true);
            txtQuantity.setBackground(Color.WHITE);
            //change the text 'edit' button to 'save edit' 
            btnEdit.setText("Save Edit");
        } else {
            // Validate inputs
            if (!pm.isPositiveInteger(txtQuantity.getText(), "Quantity") ||
                !pm.isPositiveDouble(txtUnitPrice.getText()) ||
                !pm.isValidID(txtPOID.getText(), "PO", 3, "PO ID", this) ||
                !pm.isValidID(txtItemID.getText(), "ITEM", 3, "Item ID", this) ||
                !pm.isValidID(txtSupplierID.getText(), "SUP", 3, "Supplier ID", this) ||
                !pm.isValidID(txtRequisitionID.getText(),"PR", 3, "Requisition ID", this)) {
                return;
            }

            // Update row
            int row = tblPOs.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tblPOs.getModel();
            JTextField[] fields = {
                txtPOID, txtItemID, txtItemName,
                txtQuantity, txtSupplierID,
            };
            for (int i = 0; i < 4; i++) {
                model.setValueAt(fields[i].getText(), row, i);
            }

            // Update total, date, status
            double quantity = Double.parseDouble(txtQuantity.getText());
            double unitPrice = Double.parseDouble(txtUnitPrice.getText());
            double total = quantity * unitPrice;
            model.setValueAt(String.format("%.2f", total), row, 8);
            model.setValueAt(java.time.LocalDate.now().toString(), row, 9);
            model.setValueAt("Pending", row, 10);
            model.setValueAt("Lee", row,11);

            txtQuantity.setEditable(false);
            txtQuantity.setBackground(new Color(204, 204, 204));
            btnEdit.setText("Edit");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        handleClose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tblPOsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPOsMouseClicked
        int row = tblPOs.getSelectedRow();
        if (row != -1) {
            DefaultTableModel model = (DefaultTableModel) tblPOs.getModel();

            // Map only required indices
            int[] indices = {0, 1, 2, 3, 4, 6, 7, 11};
            JTextField[] fields = {
                txtPOID, txtItemID, txtItemName, txtQuantity,
                txtSupplierID, txtRequisitionID, txtUnitPrice, txtPMName
            };

            for (int i = 0; i < fields.length; i++) {
                fields[i].setText(model.getValueAt(row, indices[i]).toString());
            }
        }
    }//GEN-LAST:event_tblPOsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblPOs.getSelectedRow();
        if (row != -1) {
            DefaultTableModel model = (DefaultTableModel) tblPOs.getModel();
            model.removeRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblPOs.getModel();
        List<String[]> data = new ArrayList<>();
        for (int i = 0; i < model.getRowCount(); i++) {
            String[] row = new String[12];
            for (int j = 0; j < 12; j++) {
                row[j] = model.getValueAt(i, j).toString();
            }
            data.add(row);
        }
        pm.writeFile("PO.txt", data);
        JOptionPane.showMessageDialog(this, "Purchase orders saved.");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtRequisitionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequisitionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequisitionIDActionPerformed

    private void txtPMNameComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtPMNameComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPMNameComponentRemoved

    private void txtPMNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPMNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPMNameActionPerformed

    private void txtSupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierIDActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String query = txtSearch.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tblPOs.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblPOs.setRowSorter(sorter);

        if (query.isEmpty()) {
            sorter.setRowFilter(null); // Show all
        } else if (query.equals("rejected")) {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)rejected", 9)); // Column 9 = status
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query, 0)); // Column 0 = PO ID
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPOs;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtPMName;
    private javax.swing.JTextField txtPOID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRequisitionID;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
