/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import FinanceManager.FMHome;
import InventoryManager.IMMainPage;
import PurchaseManager.PMPurchaseManagerDashboard;
import SalesManager.SMHomePage;
import User.LoginPage;

/**
 *
 * @author Hao Zhen
 */
public class AdminMainPage extends javax.swing.JFrame {

    private String uname;
    Admin admin = new Admin();
    
    public AdminMainPage(String uname) {
        initComponents();
        this.uname = uname;
        lblName.setText(uname + " | Administrator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        manageUserBtn = new javax.swing.JButton();
        salesMngBtn = new javax.swing.JButton();
        purchaseMngBtn = new javax.swing.JButton();
        inventoryMngBtn = new javax.swing.JButton();
        financeMngBtn = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        viewLoginBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Main Page");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Welcome, Admin");

        manageUserBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        manageUserBtn.setText("Manage User");
        manageUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserBtnActionPerformed(evt);
            }
        });

        salesMngBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        salesMngBtn.setText("Sales Manager Page");
        salesMngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesMngBtnActionPerformed(evt);
            }
        });

        purchaseMngBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        purchaseMngBtn.setText("Purchase Manager Page");
        purchaseMngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseMngBtnActionPerformed(evt);
            }
        });

        inventoryMngBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        inventoryMngBtn.setText("Inventory Manager Page");
        inventoryMngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryMngBtnActionPerformed(evt);
            }
        });

        financeMngBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        financeMngBtn.setText("Finance Manager Page");
        financeMngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeMngBtnActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        logoutButton.setText("Logout>");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblName.setText("HZ | Administrator");

        viewLoginBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewLoginBtn.setText("View Login History");
        viewLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseMngBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesMngBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventoryMngBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(financeMngBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(lblName)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblName)))
                .addGap(18, 18, 18)
                .addComponent(manageUserBtn)
                .addGap(18, 18, 18)
                .addComponent(salesMngBtn)
                .addGap(18, 18, 18)
                .addComponent(purchaseMngBtn)
                .addGap(18, 18, 18)
                .addComponent(inventoryMngBtn)
                .addGap(18, 18, 18)
                .addComponent(financeMngBtn)
                .addGap(18, 18, 18)
                .addComponent(viewLoginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserBtnActionPerformed
        AdminManageUserPage manageUserPage = new AdminManageUserPage(uname);
        manageUserPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_manageUserBtnActionPerformed

    private void purchaseMngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseMngBtnActionPerformed
        new PMPurchaseManagerDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_purchaseMngBtnActionPerformed

    private void inventoryMngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryMngBtnActionPerformed
        new IMMainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inventoryMngBtnActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginPage loginpage = new LoginPage();
        loginpage.setVisible(true);
        admin.Logout();
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void salesMngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesMngBtnActionPerformed
        new SMHomePage(uname).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salesMngBtnActionPerformed

    private void financeMngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeMngBtnActionPerformed
        new FMHome(uname).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_financeMngBtnActionPerformed

    private void viewLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLoginBtnActionPerformed
        AdminViewHistoryLoginPage viewHistoryPage = new AdminViewHistoryLoginPage(uname);
        viewHistoryPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_viewLoginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton financeMngBtn;
    private javax.swing.JButton inventoryMngBtn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageUserBtn;
    private javax.swing.JButton purchaseMngBtn;
    private javax.swing.JButton salesMngBtn;
    private javax.swing.JButton viewLoginBtn;
    // End of variables declaration//GEN-END:variables
}
